### ISSUE TITLE
The direct of the Animation never changed 

### ISSUE THREAD

**Issue by tariqmaged-bbn** [dokgi88/TanibleView#1]
Hello...I tried your Library and find it very easy but when i fill the table view with a data from the network the direction of the animation always be from the top and never changed ..here is a piece of the code and i also set the direction in the viewDidLoad...

   DataServices.instance.getAboutArr { (success, slideArr) in
            if success {
                self.titleArr = slideArr!
                self.tableViewAbout.reloadData()
                self.tableViewAbout.direction = .inPlaceFadeIn
                self.tableViewAbout.beginUpdates()
                self.tableViewAbout.endUpdates()

            }
        }

**Comment by dokgi88** [comment]
I did not know the issue was registered. Sorry to confirm late.
Currently, animation is implemented to run at the time of func draw (_rect: CGRect).
I will update the reload animation function by checking the issue part.

**Comment by dokgi88** [comment]
@tariqmaged-bbn 
Added reload function. 
Please update to version 1.1.0.

Example of using reload
```
DataServices.instance.getAboutArr { (success, slideArr) in
   if success {
      self.titleArr = slideArr!
      self.tableViewAbout.direction = .inPlaceFadeIn
      self.tableViewAbout.reload()
   }
}
```
